### ISSUE TITLE
please remove the "Display source code" section

### ISSUE THREAD

**Issue by aoloe** [jacobwb/hashover-next#115]
please, remove the 

    // Display source code

sections.

it's a clever hack, but we have github for browsing the source code :-)

**Comment by jacobwb** [comment]
Displaying the source code via the software produced by the source code is a requirement of the GNU Affero General Public License. People make changes to their local copies of HashOver without contributing those changes to GitHub or to me personally. Which is all well and good, but if there were no way to obtain the source code of their modified versions, we would never know what they've changed, and that violates the AGPL.

**Comment by aoloe** [comment]
i was not aware of it.

i had a read the gnu affero license.

i'm not a lawyer but:

"""
If your software can interact with users remotely through a computer network, you should also make sure that it provides a way for users to get its source. For example, if your program is a web application, its interface could display a "Source" link that leads users to an archive of the code. There are many ways you could offer source, and different solutions will be better for different programs; see section 13 for the specific requirements.
"""

seems not to be strict in the way you provide the sources. it's not the software that should provide the source, but the programmer should give the user a way to get the source

so: the developer could specify a url where her source code is available.

i think that adding two entries in "settings" for the original sources repository (the one of yours) and for the forked sources repository would be a better solution.  
those two links (only the first for installs directly coming from your repository) would then be shown in the footer of the comments form.

that would look more "professional" to me.

i'm willing to write a patch for it.

in any way, if somebody does not provide the sources, there is nothing you can really do to force her to stop using a modifying version of your code... we're all so small...
also for that reason i would use the least invasive solution.

on a side note:  
personally, i've used a similar code as yours to show the code of a script in the (recent) past. but it was a short term hack.  
i've never seen it in production code.

**Comment by jacobwb** [comment]
I sincerely doubt most people who modify HashOver will bother to provide and maintain proper source code of their modified version. There may be a better way to handle this, but I'm looking at making user's modified versions automatically compliant with the AGPL, and this is the best way so far.

> there is nothing you can really do to force her to stop using a modifying version of your code

I am prepared to go to the Software Freedom Conservancy, or one of my lawyer friends, should I ever need to enforce the license.

**Comment by aoloe** [comment]
personally, i'm convinced that nowadays, most people doing interesting changes to your software, will do so by forking it on github.

the rest of the people will not do anything interesting with it (or anything you will want to merge) or will be able to remove the protection you're putting in there and you'll never know that they're using your code.

it's up to you. but i don't plan to keep the link to the autogenerated source code view, in the version i'm going to publish (if i can get hashover to work correctly for me... since for now i'm still working on getting it to cleanly show in my setup...).

**Comment by jacmoe** [comment]
I am just wondering why you insist on AGPL ?
For a fullblown api with 1000s of source code files it might be appropriate, however for a commenting module that is meant to be integrated with existing websites I would really like that Hashover carried a more liberal license, like MIT.
You said yourself that there is no guarantee that people will contribute their changes back, even under the AGPL.
I am not going to hold my breath because I have a feeling that you won't change the license, but having to carry a 'show sourcecode' link on my site is something that I won't do.
I have two options: commenting out the link generate code in htmloutput.php or stop using Hashover (which is a pity).
I would not license any of my php/javascript libraries under the AGPL because it is overkill.
At least change it to GPL?
I have no axe to grind with the FSF, but in this case I urge you to reconsider and at least drop the 'A' from the license.
Simply because it is meant to be integrated. And because it is not a stand-alone application (in which case it would make perfect sense).

Thanks. :)

**Comment by jacmoe** [comment]
Sorry for harping on, but this is important (because I really like this project):
>
>
>The AGPL is based on the GPL, not the LGPL. It does not contain any linking exceptions, and any >work using AGPL code (linked or otherwise, modified or not) must also be AGPL licensed and >distributed.
>
>Using separate processes can circumvent the (A)GPL, but this is murky ground. If your end >application depends on the external process, such that it wouldn't function properly without it, then >it would be considered a derived work of the AGPL software.
>
>In most cases where people use separate GPL applications in closed source programs, they >provide the GPL work as an optional extension, or an alternative back-end to some other piece of >code etc.
>
>The (A)GPL work cannot be distributed alongside the final application even as a separate app (eg, >putting them into the same archive or repository), although it's fine to provide instructions on >where to find the GPL work and how to use it with your app.
>

I do respect copyleft, FSF, etc. but this is **meant** to be integrated **into** other people's web applications, so I can't see why it couldn't be put under the MIT (or similar) license.
If it were a stand-alone application, it would be different - WordPress is GPL, isn't it? but not in this case.

If you are reading this, then I kindly ask you to at least reconsider. :)

In my experience, people will contribute back to the project if they find it worth their while to do so, not because of the license.
However, in order to attract more people, it would be advisable to lower the bariers of entry.

Thanks, again, for listening.

**Comment by jacobwb** [comment]
@jacmoe

> I am just wondering why you insist on AGPL ?

Because it is the only license appropriate for server-side code.

> For a fullblown api with 1000s of source code files it might be appropriate, however for a commenting module that is meant to be integrated with existing websites I would really like that Hashover carried a more liberal license, like MIT.

I haven't counted, but HashOver is probably well over 1,000 lines of source code. HashOver is a standalone application, it is not a module. The primary way it's intended to be used is via a JavaScript tag, this means it doesn't "infect" non-AGPL code. HashOver can be used as a normal PHP class and return HTML, and for that use case maybe some other license might make sense, and I'm open to have the conversation, but a license like LAGPL doesn't exist as far as I know.

> You said yourself that there is no guarantee that people will contribute their changes back, even under the AGPL.

I never said this. I said people will simply overlook, or be unaware of that requirement, so it's better that this process be done for them.

> I am not going to hold my breath because I have a feeling that you won't change the license, but having to carry a 'show sourcecode' link on my site is something that I won't do.
> I have two options: commenting out the link generate code in htmloutput.php or stop using Hashover (which is a pity).

That is a violation of the license.

You may comment out the lines for displaying the source code, and offer the source code elsewhere, but removing the link to the source code is essentially revoking your "written offer ... to give anyone who possesses the object code ... a copy of the Corresponding Source for all the software in the product that is covered by [the] License, from a network server at no charge."

You must both maintain an exact copy of your modified version for public download somewhere, and ensure that a link to that download is also publicly displayed by your modified version. 

You may hide that whole bottom row of links with CSS, if you like:

```css
#hashover-end-links {
    display: none;
}
```

Or just the problematic links:

```css
#hashover-source-link,
#hashover-javascript-link {
    display: none;
}
```

It's worth noting, however, that these links will be removed in the future, they are only there to make it easier for potential developers to find the code for this project. They were put there *before web browsers had code inspection tools*. Before they can be removed a proper link must be placed elsewhere in the code, probably as a comment in the JavaScript code, but a similar thing isn't possible in PHP mode, hence why the source code links are still there.

A possible solution -- one that @aoloe might also find acceptable -- is to disable the "display source code" when the user has entered a URL for their modified version in the settings, possibly redirecting the user to the source code URL when they request the source code the normal way.

> I would not license any of my php/javascript libraries under the AGPL because it is overkill.
> At least change it to GPL?
> I have no axe to grind with the FSF, but in this case I urge you to reconsider and at least drop the 'A' from the license.

That would defeat the purpose. If the LAGPL existed, I would use that.

> Simply because it is meant to be integrated. And because it is not a stand-alone application (in which case it would make perfect sense).

It is not meant to be integrated, at least not in the conventional sense (i.e. linking to C libraries at compile time, thereby creating a single binary blob).

> Sorry for harping on, but this is important (because I really like this project)

Thank you for the interest. But please don't quote Stack Exchange.

Almost all of that quotation is wrong. You only have to license derivative works under AGPL if you incorporate the AGPL code directly into your non-AGPL code. So, in JavaScript mode this is impossible, yay, but in PHP mode doing a simple `$hashover = new HashOver ();` might mean you need to license the whole work under AGPL, however, if the program can still function without HashOver, like by putting an if statement to skip HashOver if it doesn't exist, then you're all good.

Considering that Stack Exchange question was about how MongoDB uses the AGPL, and MongoDB is doing just fine, I'd say AGPL isn't all that problematic. There is an argument to be made that perhaps the APIs should be lax, but the core of HashOver will likely remain AGPL.

> I do respect copyleft, FSF, etc. but this is meant to be integrated into other people's web applications, so I can't see why it couldn't be put under the MIT (or similar) license.

Because that would defeat the purpose.

**Comment by jacmoe** [comment]
Thank for taking the time to answer my questions.

I respect your decisions, and it didn't occur to me that using HashOver via a script tag actually is akin to make use of generated output and not incorporating the library itself.

I am aware that you can do some css magic to hide the aforementioned links, but I have nothing a link back to the project, and maybe a classy looking button.
In my book, and probably the FSF book, that is making the source code available. Provided that the link ends up here at Github.

I quoted from Stack Exchange because, as English is not my first language, that was the best explanation - or an attempt at such - I could muster. Sorry about that. :)

If I didn't care about your project, I wouldn't have bothered writing.
I still firmly believe that your choice of license is overkill.
But you have a reason for having chosen it, and it is fine by me.
Especially since you have made it clear that it is only reference in a script tag.
So all is good.

I hope that there will be a flexible way of theming it. That would be great.

**Comment by aoloe** [comment]
hi @jacobwb while i have no problems with the AGPL for my current project and i have no issue with contributing to an AGPL project, i must admit that i'm not really happy with your licensing choice either:

- assigning my copyright to you is an issue! (if i contribute any greater peace of code to a *GPL i want it to stay forever *GPL for everybody. i've agreed in the past to an exception and i regret it).

- as far as i can judge, hashover provides a comment engine for "personal" use. it's not shaped in a way that it could provide comments as a service on a broad scale: i don't see somebody wanting to change it in a significant way, refusing to publish / contribute back his changes (well, if that was the goal, he should have started from scratch. really), and you being interested in her code!

- i want comment engines to be available to the big masses. for my use (providing feedback on free software projects), i consider it a serious issue to depend on a few proprietary services without any free alternative being available (i mean: if you start using it, you have no chance to migrate out of it!).   such an engine should be as available and as hackable as possible. the AGPL is not the best license for achieving this goal.

- and i already expressed my opinion about the "sources" link and the way you're providing the a source view from the file itself. (nice to see you aknowledge it. but if you really want to provide the sources from your own code, you should consider creating a source viewer written in php and distribute it with hashover... and not "infect" each file with this function (but, as said: if somebody hacks on AGPL code and does not use any public repository, you probably do not want to use her crappy code or she will be hiding it from you anyway!).


all in all, i have a few more issues with the choices you have made for hashover. during my work on a simpler json storage engine, i started thinking wether i should really try to bend it to match your current code or if it would be easier to keep in mind all the good things you have done and start from scratch.
you might have seen from my github activity (it's a mess... i know!) that i'm giving the second way a try. without borrowing any line of code from hashover (since if it's my effort i want it to be licensed under a liberal license), i'm working on a comment engine that is built in what i consider a "cleaner" and modern way.
(between hashover and hashover-next there is a huge improvement! but i still have some concerns...)
currently, i'm still in the phase where i'm checking if it's worth the effort to create my own engine... i guess that the line will be drawn at the end of next week: if by then i have a version 1.0 that i can use, i probably will stick to it, otherwise i think i will explain you the changes i've made and suggest you to integrate them in hashover. i hope that  having a working prototype will help the discussion :-)

have fun
a.l.e

**Comment by jacobwb** [comment]
> assigning my copyright to you is an issue! (if i contribute any greater peace of code to a *GPL i want it to stay forever *GPL for everybody. i've agreed in the past to an exception and i regret it).

Contributing to HashOver does not require that you assign your copyright to me. I only ask that contributions place myself as one of the copyright holders.

For example, instead of this...

> Copyright (c) 2015 Ale Rimoldi

You should do this...

> Copyright (c) 2015 Ale Rimoldi, Jacob Barkdull

This means we both have ownership, and therefore usage rights to the work. This isn't necessary when only changing an existing work, as I am the only copyright holder in that case and all non-trivial contributions can't be claimed by the contributor anyway. For entirely new works, both my name and the contributors names should exist on the copyright notice.

> as far as i can judge, hashover provides a comment engine for "personal" use. it's not shaped in a way that it could provide comments as a service on a broad scale: i don't see somebody wanting to change it in a significant way, refusing to publish / contribute back his changes (well, if that was the goal, he should have started from scratch. really), and you being interested in her code!

HashOver will eventually support multiple websites with a single installation (with independent configurations), single sign-on (SSO) to allow login information to be passed to HashOver from a CMS or third-party source (OAuth, OpenID, etc), thread differentiation will be based on IDs with URLs being an optional basis (meaning one could have a thread for each paragraph of an article if desired), and many other general use features are planned to be implemented at some point in the future.

HashOver is suitable for personal use, yes, and should remain as slim and efficient as possible for such use cases, but it is by no means designed only for personal use.

> i want comment engines to be available to the big masses. for my use (providing feedback on free software projects), i consider it a serious issue to depend on a few proprietary services without any free alternative being available (i mean: if you start using it, you have no chance to migrate out of it!). such an engine should be as available and as hackable as possible. the AGPL is not the best license for achieving this goal.

I agree with this.

I disagree that the AGPL isn't the best license here. This hackability must be protected. I see it as a waste of effort to create a useful project, only to allow people to deny other users that same freedom to hack on their improved version of the software, keeping their improvements to themselves.

> and i already expressed my opinion about the "sources" link and the way you're providing the a source view from the file itself. (nice to see you aknowledge it. but if you really want to provide the sources from your own code, you should consider creating a source viewer written in php and distribute it with hashover... and not "infect" each file with this function (but, as said: if somebody hacks on AGPL code and does not use any public repository, you probably do not want to use her crappy code or she will be hiding it from you anyway!).

I've considered the "source code viewer" idea before, my concern there is the possibility of the viewer showing the source code to files that aren't part of HashOver, as that would be a security risk. However, I do dislike the fact that the source code "function" is probably the only duplicate code in the entire project. Having to change each file when making a change to how source code is displayed is tedious.

I disagree with the notion of automatically assuming private code to be crappy. Probably the majority of useful modifications are made in "private", as in not posted to GitHub or the like, and because of HashOver's unique attention to compliance with the license, I've been able to view every useful modification I've stumbled across so far.

> all in all, i have a few more issues with the choices you have made for hashover. during my work on a simpler json storage engine, i started thinking wether i should really try to bend it to match your current code or if it would be easier to keep in mind all the good things you have done and start from scratch.
you might have seen from my github activity (it's a mess... i know!) that i'm giving the second way a try. without borrowing any line of code from hashover (since if it's my effort i want it to be licensed under a liberal license), i'm working on a comment engine that is built in what i consider a "cleaner" and modern way.
(between hashover and hashover-next there is a huge improvement! but i still have some concerns...)
currently, i'm still in the phase where i'm checking if it's worth the effort to create my own engine... i guess that the line will be drawn at the end of next week: if by then i have a version 1.0 that i can use, i probably will stick to it, otherwise i think i will explain you the changes i've made and suggest you to integrate them in hashover. i hope that having a working prototype will help the discussion :-)

I'm looking forward to what you come up with. HashOver can always benefit from competition.

But just for the record, AJAX is coming to HashOver soon. I don't know what you mean by "modern way", but I assume pulling and posting comments via XMLHttpRequest is part of that.

**Comment by jacmoe** [comment]
I am wondering if it's possible to tell HashOver to use your theme?
If it's not, I'd like that to be supported to enable us to customize the looks without having to hack around in the source. :)

Looking forward to seeing Ajax in HashOver - will it be plain javascript or jQuery?

**Comment by jacobwb** [comment]
> I am wondering if it's possible to tell HashOver to use your theme?
> If it's not, I'd like that to be supported to enable us to customize the looks without having to hack around in the source. :)

I'm not sure what you mean by this, but you can specify what theme you want to use in the settings.

If you want to make your own theme without messing with the default, you can make a copy of the default (`hashover/themes/default`) and rename it to something else, and then set the `public $theme` to your theme's name. The theme features of HashOver include normal CSS stuff and an HTML template that allows you to move the actual elements around.

Beyond that, you can add CSS stuff for HashOver in your site's main theme, and then disable HashOver adding its CSS to the page, with `public $appendsCSS = false;` in `settings.php`

> Looking forward to seeing Ajax in HashOver - will it be plain javascript or jQuery?

Everything in HashOver is plain JavaScript, and it will remain that way :-)

**Comment by jacmoe** [comment]
Thanks @jacobwb :)
