### ISSUE TITLE
Place all files in one main subdirectory, please.

### ISSUE THREAD

**Issue by taophp** [jacobwb/hashover-next#124]
Have you considered the possibility to place all your files in one subdirectory ?
I mean: currently, you require that the hashover.js file to be placed at the root of the web site. This implied, when using git, that the hashover main directory and of the website root directory have to be the same. So, if someone, as I did, use git to clone hashover in his project, the .git directory have to be used for hashover, at least if he wants to contribute, as I do.
This is a problem if the project has to be manage with Git. I don't know how the project and hashover could share the same `.git` directory: if there is anyway to do so, please, point me to some documentation. If no, so please, could you design your project to make it fit in the `hashover-next` directory that the `git clone` command create, as a subdirectory of the root.
As Git is often recommended as a companion tool to manage static websites, as with [Jekyll](http://jekyllrb.com), and as Hashover seems a very good tool for static websites, you should really consider to make this move. It should be great for many of us.

**Comment by jacobwb** [comment]
@taophp

All the files will go into a single directory eventually, but I will not be tracking the `hashover/` directory itself, as that would be a nuisance for websites already using `hashover-next` once HashOver 2.0 is officially released. They would all need to change their script tags to point to the new locations. This `hashover-next` situation may need to happen again eventually, and I don't want to cause the aforementioned inconvenience more than once.

**Comment by taophp** [comment]
I'm not sure I really understand the problem, but it may be because it does not really exist. If you considered the pull request https://github.com/jacobwb/hashover-next/issues/125 and read the code carefully, you'll see that I did not change the directories structure. All is preserved. You may or may not use hashover from the webroot or from the directory `hashover-next` or any other subdirectory you need. You do not have any change to make it work, but you now can if you need it.
The fact is that when you run the command `git clone https://github.com/jacobwb/hashover-next.git`, git creates a directory `hashover-next`. You may rename this directory, its name is not tracked by Git, only its contents. The fact is that for many users, including me, it's better to move this directory in a subdirectory of the webroot, so you can track your whole site with git.
But if you don't want to run hashover-next in a subdirectory to avoid changing script linking, you can. I wrote my branch with this requirement in mind. It's not a breaking change.

**Comment by jacobwb** [comment]
> If you considered the pull request #125 and read the code carefully, you'll see that I did not change the directories structure. All is preserved. You may or may not use hashover from the webroot or from the directory hashover-next or any other subdirectory you need. You do not have any change to make it work, but you now can if you need it.

Untrue. This commit changes HashOver to assume it's nested two directories deep...

```diff
- $this->httpRoot		= '/' . basename ($dirname);
+ $this->httpRoot		= dirname(dirname($_SERVER['PHP_SELF']));
```

Which for every user of HashOver up until now isn't true. In PHP mode it's even worse, since you're basing the directory name on the `PHP_SELF` path, the directory will most certainly lose two of its parents -- how sad :( -- as the PHP file instantiating HashOver will most likely be stored at the web root. This will break avatars, posting comments, etc.


> The fact is that when you run the command git clone https://github.com/jacobwb/hashover-next.git, git creates a directory hashover-next. You may rename this directory, its name is not tracked by Git, only its contents. The fact is that for many users, including me, it's better to move this directory in a subdirectory of the webroot, so you can track your whole site with git.
But if you don't want to run hashover-next in a subdirectory to avoid changing script linking, you can. I wrote my branch with this requirement in mind. It's not a breaking change.

I understand the desire to have HashOver in a sub-directory, and for your use it's a completely logical move. I believe I have mentioned in other issues that HashOver would eventually reside entirely in one directory, and that is now the case with the latest code. I am simply looking to maintain a stable and smooth transition from 1.0 to 2.0. Please understand.

Pull the latest code and you should be able to do what you need.

Like so...

```html
<script type="text/javascript" src="/hashover-next/hashover/hashover.js"></script>
```

I appreciate your interest in contributing, improvements are welcome.

:-)

**Comment by taophp** [comment]
> Please understand.

No problem. I understand very well. It's your project, it have a long history. You're the boss, very aware of your choices and the reasons that command them. I'm new to it, enthusiastic, but with a quite naive approach. If, in the future, for one reason or another, we disagree strongly, this should not be a problem at all: I *may* fork your project, politely, at least for my own use: that's the beauty of free software.

> I appreciate your interest in contributing, improvements are welcome.

Thanks for this. So there is mutual appreciation.
Thanks to have take the time for this complete and precise answer.
