### ISSUE TITLE
JSON settings file should not remotely readable

### ISSUE THREAD

**Issue by taophp** [jacobwb/hashover-next#130]
JSON file is remotely readable. As some features may required some secrets informations, as it is a basic security policy to not publish the configuration of an on-line running application, I suggest to move to another design by default. Even if JSON settings file ability is preserved for compatibility purposes, I think that Hashover should move to another default settings architecture, such as the use of a PHP file like many others applications.
Please, let me know what you think.

**Comment by jacobwb** [comment]
It's unfortunate that JSON files are inherently readable, yes. I have considered the possibility of the `secrets.php` file making a return, but perhaps in a more simplistic way.

That said, there is a reason for JSON being used. It is writable.

By that I mean JSON is easily parsed, edited and written back to a file with PHP's `json_decode`, `json_encode` and `file_put_contents` functions. And this is necessary because a "control panel"-type feature is planned. Changing settings will be done using this "control panel" and not by changing the files, this will be much easier for all users. Also comment moderation and deletion will be done there, editing existing comments, and editing page titles and URLs as well.

PHP just doesn't make for good configuration files in this case.

**Comment by arktype** [comment]
You could create an .htaccess file that restricts access to the config directory (included by default). Users of Nginx or other servers would need to add their own flavor manually, of course. Alternatively, and I'm not sure this would work/be a good idea, the JSON could be assigned as a variable in a PHP file and included when needed.

**Comment by jacobwb** [comment]
Yes, `.htaccess` is always an option. However, not all servers allow the use of `.htaccess` files. HashOver should be secure by itself, without extra reliance on user configuration. Having JSON stored in a PHP file would indeed not work. The main issue is writing the file, not storing the data as JSON. PHP files aren't meant to be written programmatically, whereas XML and JSON are.
