### ISSUE TITLE
This comment is pending approval. 

### ISSUE THREAD

**Issue by TStein1984** [jacobwb/hashover-next#137]
Hello,

I have a problem with the hashover next. The system is running well, but when I try to use the option 

- public $usesModeration		= true;

than I have no option to approve the comments. It's not posible by the information mail and also not during the login as admin. 

Attached I send the view without and with login.

Thank you for your help in advance.

Best regards 

Thomas
![picwithlogin](https://cloud.githubusercontent.com/assets/22123632/18414089/facbd348-77bd-11e6-8722-c738cac3c6c3.JPG)
![picwithoutlogin](https://cloud.githubusercontent.com/assets/22123632/18414090/facc0480-77bd-11e6-8dd6-5bdfe15bd70d.JPG)

**Comment by jacobwb** [comment]
Hello @TStein1984,

This is a known limitation. In the future the admin login and moderation of comments on individual pages will be removed in favor of a "Control Panel" feature where all comments will be editable, delete-able, and moderate-able from a single place.

For this reason moderation from the admin login isn't possible, moderation has to be done by editing the `status` of the comments themselves. Moderation is basically beta at this point.

Nonetheless, there should be a way to moderate comments in the meantime. I will look through the code and implement a way to moderate comments from the admin login.

It shouldn't take long, it will likely be done before you even read this, but I will post here again when I commit the changes. I hope you will be up for testing out the new code.

**Comment by jacobwb** [comment]
Hello @TStein1984,

Comment moderation from the admin login has now been implemented. Simply pull the new files -- but keep your old `settings.php` because that file hasn't changed -- and you will see a dropdown menu that will let you change the comment's moderation status...

![screenshot from 2016-09-20 08-53-56](https://cloud.githubusercontent.com/assets/4677622/18678520/2cb6153a-7f11-11e6-8689-002fbe6ad0bc.png)

Choose "Approved" from that menu and save the comment...

![screenshot from 2016-09-20 08-56-32](https://cloud.githubusercontent.com/assets/4677622/18678574/4b6720aa-7f11-11e6-8626-e9a0445caa1a.png)

I hope it works well for you, please close this issue if it does.

The functionality might be presented differently in the future, as icons instead of a dropdown menu for example, but let me know what you think.

Any feedback would be greatly appreciated.
