### ISSUE TITLE
Allows limited use of HTML?

### ISSUE THREAD

**Issue by jorgesumle** [jacobwb/hashover-next#147]
Where is this documented? `<a>` and `<em>` don't work for me. How can I allow them?

Here is what I got from a comment:

![captura de pantalla de 2017-02-25 19 30 48](https://cloud.githubusercontent.com/assets/14212780/23333729/f14d34ea-fb90-11e6-9617-2b7112e432a0.png)

**Comment by jacobwb** [comment]
Yes, limited HTML and limited Markdown are allowed in comments. The hyperlink anchor tag is not allowed because it can be used by attackers, spammers, and phishers. Instead, URLs automatically become links, allowing people to use links, while also allowing users to see what they actually link to.

This is documented here:

> http://tildehash.com/?page=hashover#html-in-comments

That said, there is no reason why `<em>` isn't supported, so I have added it. Along with `<big>`, `<small>`, `<strong>`, `<sub>` and `<sup>`. I don't think this is something that can be made configurable, so acceptable HTML tags will just have to be manually added to the code as they are needed.

**Comment by jorgesumle** [comment]
Thanks for the quick and helpful response.

P.D. I don't know why, but the update to https://github.com/jacobwb/hashover-next/commit/94ce2001bc92b06c2dd1eb1ead7a22aca41e5ab6 broke my hashover-next version. I was using json, and it no longer works. With xml it works fine though.

**Comment by jacobwb** [comment]
Thanks for letting me know! JSON should be fixed now. Looks like I left that file unfinished before pushing the new code to GitHub, nothing major.

**Comment by jorgesumle** [comment]
I created a wiki page, so that future users know how it works: https://github.com/jacobwb/hashover-next/wiki/HTML-in-comments

Maybe, we should start documenting it in a Wiki. I don't like depending Github very much, so if you like another alternative, such as documenting the proyect with Sphinx or any similar tool, you can count with my help too. What do you think?

**Comment by jacobwb** [comment]
> I created a wiki page, so that future users know how it works: https://github.com/jacobwb/hashover-next/wiki/HTML-in-comments

Nice, but this is something that needs to be presented to the people posting comments as well. I am working on a way to do that, I'm not sure I like how I've done it, but I will post the code soon.

> Maybe, we should start documenting it in a Wiki. I don't like depending Github very much, so if you like another alternative, such as documenting the proyect with Sphinx or any similar tool, you can count with my help too. What do you think?

I don't like depending on Github either, but I also don't like using tools like Sphinx. The documentation should be in simple manually written HTML, Markdown, or text. I have been meaning to create a proper website for HashOver, with proper documentation, downloads, and themes, etc, but for me writing code and improving HashOver takes priority over documenting it.

With that said, if you want to write more Wiki pages about how to use HashOver, I am willing to answer any questions you may have, to help you explain it clearly. Such Wiki pages would help greatly in writing the final documentation for the website.

**Comment by jorgesumle** [comment]
> I don't like depending on Github either, but I also don't like using tools like Sphinx. The documentation should be in simple manually written HTML, Markdown, or text. I have been meaning to create a proper website for HashOver, with proper documentation, downloads, and themes, etc, but for me writing code and improving HashOver takes priority over documenting it.

Maybe, I can help you with the website. I find the [Guix website](https://www.gnu.org/software/guix/) very inspiring, maybe we can do something similar. What ideas do you have? Do you have any preference for a tool to build the website? For example, using a particular programming language, a static site generator, just a traditional website...

> With that said, if you want to write more Wiki pages about how to use HashOver, I am willing to answer any questions you may have, to help you explain it clearly. Such Wiki pages would help greatly in writing the final documentation for the website.

OK, I'll write more wiki pages in the following days, with the idea of moving them to the final website later. I think that most information is very well documented in the HashOver website. I'll try to avoid or update the outdated information and include some more information from this development version.

**Comment by jacobwb** [comment]
> Maybe, I can help you with the website. I find the Guix website very inspiring, maybe we can do something similar. What ideas do you have?

Design-wise I'm thinking something like [blender.org](https://www.blender.org/), with documentation like that of [GTK+ 3](https://developer.gnome.org/gtk3/stable/GtkGrid.html) but with the polish of Firefox's [release notes](https://www.mozilla.org/en-US/firefox/52.0/releasenotes/). The documentation style is more-or-less what I'm using now, for example the [HashOver 1.0.1, the release that should not have happened!](http://tildehash.com/?article=hashover-1.0.1-the-release-that-should-not-have-happened) post, but I would like for it to be done better and easier to update, etc.

> Do you have any preference for a tool to build the website? For example, using a particular programming language, a static site generator, just a traditional website...

My website right now is using old CMS software I wrote years ago. I have since wrote new CMS software with the specific intent of using it for HashOver and my other software. This new CMS supports generating static HTML with JavaScript minification.

As you can probably tell, I don't like depending on tools for my website creation either.

> OK, I'll write more wiki pages in the following days, with the idea of moving them to the final website later. I think that most information is very well documented in the HashOver website. I'll try to avoid or update the outdated information and include some more information from this development version.

Upon the release of HashOver 2.0 I will likely also release my CMS, at that point the syntax for the HashOver documentation will be publicly available and it will be easy for you to contribute that way. Until then, the Wiki pages would be very useful. Thank you!
