### ISSUE TITLE
Why i added `$ allowedDomains` setting, but the site does not show Hashover?

### ISSUE THREAD

**Issue by myiq** [jacobwb/hashover-next#156]
If you do not add `$ allowedDomains` setting, the site will show` Hash: External use not allowed.` But add `$ allowedDomains` setting, Hashover is not realistic. What should I do?

**Comment by jacobwb** [comment]
We have since talked about this via e-mail, and the problem was a simple PHP syntax error.

For those less familiar with PHP, the expected format of the `$allowedDomains` setting is...

```php
public $allowedDomains = array (
	'*.example.com',
	'*.example.org',
	'*.example.net'
);
```

Each of the domains in the array needs to have a comma (`,`) at the end, except for the last domain. A domain by itself, for example `google.com`, will allow google.com but not `cdn.google.com` to access the HashOver files remotely. You may specify individual subdomains in the `$allowedDomains` setting, or place a wildcard `*` as the subdomain, for example `*.google.com`, to allow all subdomains.
