### ISSUE TITLE
Uncaught Error: Call to undefined method Locale::get() in /hashover/scripts/login.php:58

### ISSUE THREAD

**Issue by Halyul** [jacobwb/hashover-next#157]
```` html
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined method Locale::get() in /hashover/scripts/login.php:58
Stack trace:
#0 /hashover/scripts/hashover.php(111): Login-&gt;__construct(Object(Setup))
#1 /hashover/scripts/hashover-javascript.php(38): HashOver-&gt;initiate()
#2 {main}
  thrown in <b>/hashover/scripts/login.php</b> on line <b>58</b><br />
````
Is there anyone have some solutions to solve this?

**Comment by jorgesumle** [comment]
https://github.com/jacobwb/hashover-next/pull/158

**Comment by jacobwb** [comment]
This is odd. Someone else is having the same issue.

Can you verify for me that the `/hashover/scripts/locale.php` file has proper read permissions? Namely permissions `0644`; readable by everyone essentially.

**Comment by Halyul** [comment]
I set it `0755`

**Comment by jacobwb** [comment]
This was caused by a simple scoping issue. Namely, you likely have a package installed on your system named `php-intl` or `php5-intl` or `php7-intl`, something like that. That package adds a `Locale` class to the PHP global namespace, HashOver also has a class named `Locale`, and since one cannot redeclare classes in PHP the HashOver `Locale` class wasn't being used. The `Locale` class from the `php-intl` doesn't have the necessary `get` method.

I have now implemented namespacing, all of HashOver's classes and functions are now in the `HashOver` namespace, separated from the global scope.  This should fix the issue you're having, as well as prevent this kind of thing from happening again in the future.

Too bad PHP's namespacing is hideous.
