### ISSUE TITLE
How to install Hashover in WordPress?

### ISSUE THREAD

**Issue by LiarOnce** [jacobwb/hashover-next#159]
I want to use it,but I don't know how to install in WordPress.
So I need Installation help about WordPress.

**Comment by jacobwb** [comment]
Are you running the WordPress software on your own server, or using wordpress.com?

Getting HashOver running will depend on your setup.

**Comment by LiarOnce** [comment]
I'm running the WordPress software on my own server.

**Comment by jacobwb** [comment]
It get HashOver working in WordPress running on your own server, do the following...

1. Get HashOver (obviously)
2. Place the HashOver `hashover` directory at the root of your website.
3. Copy the "[hashover-wp-plugin.php](https://github.com/jacobwb/hashover-next/blob/master/hashover/misc/hashover-wp-plugin.php)" file into the `wp-content/plugins` WordPress directory.
4. Go to the WordPress admin page -> Plugins -> HashOver -> Activate

Let me know how it goes.

**Comment by LiarOnce** [comment]
Thanks!

**Comment by LiarOnce** [comment]
It worked,but...
![scr](https://ooo.0o0.ooo/2017/03/25/58d648b059f68.png)

**Comment by jorgesumle** [comment]
@jacobwb, why include the Wordpress plugin in the codebase? Maybe is a better idea to make the plugin independently in another repository and then submit it to the Wordpress plugin directory; else we would end up will a thousand of plugins for every CMS instead of focusing on developing the comment system and let Wordpress users, Joomla users, etc., adapt the comment system to their CMS.

**Comment by LiarOnce** [comment]
@jorgesumle I agree with you.I think that the WordPress plugin should be created separately to build a code repository,too.

**Comment by jacobwb** [comment]
@LiarOnce

Good, it works for you as well. However, I don't see what's wrong with that screenshot.

Am I missing something?

**Comment by jacobwb** [comment]
@jorgesumle @LiarOnce I agree, it's currently in the codebase just as a convenient way to pass it along. I planned to move it to either its own repository or to a new repository for all CMS plugins.

I haven't decided what way is best, what do you think?

A repository like `hashover-wp-plugin` or a new plugins/extras repository like `hashover-cms-plugins` which would hold all future CMS plugins?

**Comment by LiarOnce** [comment]
@jacobwb Well,I think 'hashover-cms-plugin' is more sutiable.

**Comment by LiarOnce** [comment]
Hashover can work properly, but there are still two problems:
1,It can't be loaded under PJAX.
2,The comment window is in the wrong position.
It should have replaced the original comment window.
In my Windows Tablet PC browsing can see more clearly:
![src](https://ooo.0o0.ooo/2017/03/25/58d681489e6f2.png)

**Comment by jorgesumle** [comment]
> I haven't decided what way is best, what do you think?

If you were to create a central repository called `hashover-cms-plugins` or something similar, then you could add each plugin as a [git submodule](https://git-scm.com/book/en/Git-Tools-Submodules), so that each plugin is managed in its own repository by its own maintainer. I'm not a big fan of putting everything in a single repository though.

If you want to keep improving the plugin you created for Wordpress in a separate repository, that would be great and better for Hashover. Remember that if Hashover gains more popularity this repository may be difficult to handle if everyone is making pull requests for their CMSs. See https://github.com/getpelican/pelican-plugins/ as an example of a bad consequence of that: many ignored pull requests.

**Comment by jacobwb** [comment]
@jorgesumle Agreed. Also, other people are probably going to create their own repositories for their plugins anyway, so I might as well place mine in its own repository as well.

**Comment by jacobwb** [comment]
@LiarOnce

Please give the new files a try and tell me if the changes help...

https://github.com/jacobwb/hashover-wp-plugin

**Comment by LiarOnce** [comment]
It works well.
![snipaste_20170326_130508.png](https://ooo.0o0.ooo/2017/03/26/58d74c53e2b64.png)

**Comment by LiarOnce** [comment]
The only question now is how to do PJAX overload currently.
