### ISSUE TITLE
Timing issue?

### ISSUE THREAD

**Issue by linuxitux** [jacobwb/hashover-next#203]
After upgrading to the latest commit I'm having a strange issue: the comment section is loading in a wrong position. That didn't happened before the upgrade.

I'm embedding hashover in a Joomla! site and loading this code at the end of every single article:

``<script type="text/javascript" src="/hashover/comments.php"></script>``

But instead of displaying the comment section below the article's content, it's showing in the right panel (inside some other module).

Any hint?

**Comment by jacobwb** [comment]
Hi, try again with the new files, please...

**Comment by linuxitux** [comment]
Solved!

**Comment by jacobwb** [comment]
Great!

For information: When using HashOver, you should place an element with the ID `hashover` on the page where you want the comments to appear, for example...

```html
<div id="hashover"></div>
```

If this element exists HashOver will always use it. However, without it HashOver "guesses" where you want the comments based on where you placed the HashOver JavaScript tag.

This guessing game is where the problem was. You're right in calling it a "timing issue", since it was caused by the introduction of asynchronous communication with the HashOver backend.

To avoid making HashOver have to guess where it is, you should use that HTML code.

**Comment by linuxitux** [comment]
Thanks @jacobwb 

I just realized some JS function was getting the DOM element with id "hashover", but inspecting the HTML code generated after loading the comments, it was already there. I tried loading the comments inside a div, but without that id. Didn't imagine the solution was so simple. I wouldn't call it a bug but a lack of a proper documentation (#206).

Thanks again!
