### ISSUE TITLE
Admin login not working

### ISSUE THREAD

**Issue by linuxitux** [jacobwb/hashover-next#204]
The credentials stored in `backend/classes/secrets.php` doesn't work. I just get a red border after pressing the "Login" button.

**Comment by jorgesumle** [comment]
They work for me.

**Comment by jorgesumle** [comment]
Did you try from `hashover-next/hashover/admin/`?

**Comment by jacobwb** [comment]
Can you login as Admin on HashOver itself?

It's worth noting the Admin name and password are both case-sensitive.

**Comment by linuxitux** [comment]
My installation path is hashover/admin.

**Comment by linuxitux** [comment]
I did not enable the password field in the front-end, I will enable it and try.

**Comment by jacobwb** [comment]
Hi, thanks for finding this bug. One of the main reasons for the administration page is to allow the editing and deletion of comments even if the password and/or user name fields are disabled, so if the admin page is not accessible with the password field disabled, that is not good, and not intentional.

This bug should now be fixed. Please close the issue if it works for you.

**Comment by linuxitux** [comment]
Thanks @jacobwb @jorgesumle 

Now it's working!
