### ISSUE TITLE
PHP mode

### ISSUE THREAD

**Issue by CyberShadow** [jacobwb/hashover-next#210]
Hi, and thank you for your work on this project.

I'm trying to get PHP mode to work with the latest version from git, and running into some trouble.

1. First, currently there is no documentation. The only instructions I found on this subject were in the changelog. This might not be a problem if integrating Hashover in PHP mode would be simple or obvious, but I haven't found such a way.

2. Following the changelog instructions:

    https://github.com/jacobwb/hashover-next/blob/7a38fd119dd27b50511d007e3ae2235ab6706a26/hashover/changelog.txt#L1186-L1202

    currently seems insufficient. It results in the error:

       <b>Fatal error</b>:  Uncaught TypeError: Argument 2 passed to HashOver\PHPMode::__construct() must be an instance of HashOver\CommentsUI, null given, called in /home/csblog/hashover-next/hashover/backend/classes/hashover.php on line 414 and defined in /home/csblog/hashover-next/hashover/backend/classes/phpmode.php:43
       Stack trace:
       #0 /home/csblog/hashover-next/hashover/backend/classes/hashover.php(414): HashOver\PHPMode-&gt;__construct(Object(HashOver\Setup), NULL, Array)
       #1 /home/csblog/www/hashovertest.php(22): HashOver-&gt;displayComments()
       #2 {main}
         thrown in <b>/home/csblog/hashover-next/hashover/backend/classes/phpmode.php</b> on line <b>43</b><br />

3. From looking at the source code, I inferred that the above code is missing calls to `$hashover->initiate()` and `$hashover->finalize()`. Adding those, there are no more errors; however, the output looks like this:

   ![screen shot 2018-03-04 at 06 33 02](https://user-images.githubusercontent.com/160894/36942879-ea91957e-1f75-11e8-836f-945da03154c4.png)

   - It looks like the form has many more fields than necessary.
   - There is a "Name" and "Password" field even though "Allow users to login" is off.
   - There is complete lack of styling. There are no references to style sheets in the generated HTML, either.

Have I missed something?

**Comment by techboyg5** [comment]
You need to load the CSS seperately like this:

    <link href="/hashover/comments.css" rel="stylesheet" type="text/css">

**Comment by jacobwb** [comment]
@CyberShadow You're on the right track. There isn't any documentation right now because it is still so not-straightforward to use, I want to make it simpler before documenting it. @techboyg5 is right, you need to declare the CSS file in your website `<head>` yourself, because HashOver in PHP mode can't do that automatically like JavaScript can.

Now, for a long overdue explanation of using HashOver in PHP mode:
```php
<?php

// Setup HashOver for use in PHP-mode, autoload class files
require ('hashover/backend/php-setup.php');

try {
    // Instantiate HashOver
    $hashover = new HashOver ('php');

    // Set page URL to create a backend thread directory
    $hashover->setup->setPageURL ('https://comments.barkdull.org/test-page.php');

    // Set page title for metadata / use in APIs
    $hashover->setup->setPageTitle ('HashOver 2.0 (development) Test Page');

    // Do some necessary setup work before loading comment files
    $hashover->initiate ();

    // Load and parse primary comment files
    $hashover->parsePrimary ();

    // Decide which comments appear in the popular comments section
    $hashover->parsePopular ();

    // Sort primary comments as configured
    $hashover->sortPrimary ();

    // Do some final setup work before outputting HTML
    $hashover->finalize ();

} catch (Exception $error) {
    // Displays exceptions in HTML paragraph tag
    echo HashOver\Misc::displayError ($error->getMessage ());
}

?>
```

You should place that kind of code in a PHP file that returns HTML, but place it before any HTML output, as HashOver needs to set a few headers. The key things you're missing is using `setPageURL` to tell HashOver what page it is on, and using `parsePrimary` to load normal comments. The other things in the code above are mostly optional, but required to get the same functionality as HashOver in JavaScript mode, also the order of the functions is important.

After that code is in place, you can now output the HashOver HTML wherever you want using the following code...

```php
<?php

try {
    // Generate interface, form, and comment HTML
    echo $hashover->displayComments ();

} catch (Exception $error) {
    // Displays exceptions in HTML paragraph tag
    echo HashOver\Misc::displayError ($error->getMessage ());
}

?>
```

I am going to close this issue, but feel free to continuing asking more questions here if necessary.

I hope this helps.

**Comment by CyberShadow** [comment]
Thanks, I had already figured something out two years ago. Sorry for not updating the issue.

**Comment by jacobwb** [comment]
No problem, I'm glad you figured it out. I'm just going through and answering some issues right now, some are quite old but I don't know who is still interested in answers so I just answer them all.
