### ISSUE TITLE
Admin Settings Do Not Save New Changes

### ISSUE THREAD

**Issue by girtsazis** [jacobwb/hashover-next#221]
I have issues saving new changes I made via mysite/hashover/admin and also via hashover/backend/classes/settings.php

1. When I make changes via administrator panel  mysite/hashover/admin i made some changes and clicked save. After page reloaded the new changes I made are not there and there were all the default settings again.
2. So i opened the file hashover/backend/classes/settings.php made the changes uploaded to my server, but in my website there is no changes again.

Here is what I changed
`public $allowsLikes		= true;	
public $collapseLimit		= 10;
public $databaseType		= 'mysql';`

**Comment by CyberShadow** [comment]
Your settings.json file is probably not writable in some way.

The changes in the PHP code have not taken effect because they are overridden by the JSON file's contents.

**Comment by girtsazis** [comment]
File permission 777 settings.json did the work for admin page. Thank you!

**Comment by linuxitux** [comment]
I deleted settings.json (following the comment by @jacobwb on #205) and it never came back. So right now I can't change any setting from the admin panel.

**Comment by CyberShadow** [comment]
Currently the version of HashOver in git master can't recreate `settings.json` [because of a bug](https://github.com/jacobwb/hashover-next/pull/213/commits/22e702f8e7f585e33830d531a2a2ec52bbfba307). You have to create a dummy file (or restore the one that game with HashOver), and make sure it is writable (the process that the HashOver PHP code runs under has write permissions to the `settings.json` file).
