### ISSUE TITLE
Please clarify policy on contributions

### ISSUE THREAD

**Issue by CyberShadow** [jacobwb/hashover-next#228]
Sorry, but I must ask:

Why have you ignored the pull requests I submitted and continued development in private, without so much as one comment on any of the issues / PRs I filed? Now there are merge conflicts that I would need to resolve, which could have been avoided by timely reviewing and integrating them. Even if I fix the merge conflicts now, there's no telling if this situation is not going to happen again.

If you are not interested in accepting contributions to your project, please clarify this in the project description and `CONTRIBUTING.md`, so that potential contributors don't waste their time.

If you need help running an open-source project, please don't be afraid to ask.

**Comment by CyberShadow** [comment]
@jacobwb Ping

**Comment by jorgesumle** [comment]
Try sending them an email, you can find it in the commit info.

**Comment by CyberShadow** [comment]
I kinda doubt the problem is things not reaching Jacob's inbox, as they have been responding to others' issues.

**Comment by jacobwb** [comment]
Hello @CyberShadow, it's nothing personal, I have just been very busy until now. I have had very little time to work on HashOver. However, more importantly is I had a backlog of e-mails from other people and older issues I have yet to address. Normally I address e-mails first and GitHub issues second, since that is the way the project was started and many of the people instrumental to the design of HashOver I only have contact with through e-mail.

I am now set to work on HashOver full time for a month or more, I hope to address every open issue and accept/reject every open pull request. So while your issues and pull requests will still not be addressed immediately, they will be by the end of the month.

As to contributing rules, there aren't many. If I like the contribution, it will be accepted, if not, I will work to get to a compromise or reject the contribution altogether. However, it is worth noting that HashOver is a personal project that I don't always have time for -- which is why I try to keep it mostly stable -- and it is very likely that there will be delays again in the future.

Contributions are welcome, I just might be slow to getting to them.

**Comment by CyberShadow** [comment]
Thank you for the reply! I am happy to hear you're going to work on HashOver again.

Perhaps, I could try to make some time too, so that we might collaborate on the issues I've ran into.

If I may make a suggestion, it is to prioritize addressing pull requests before all issues and support requests. Reviewing and integrating proposed code changes is probably the most important task of a software project maintainer: bugs could eventually be fixed by others, but if there is no one to accept said fixes, the project can't move forward, and it leads to wasted work and forks. I follow this rule too for [the open-source projects I maintain](https://github.com/CyberShadow?utf8=%E2%9C%93&tab=repositories&q=&type=source&language=), and I highly recommend it.
