### ISSUE TITLE
404 on logout

### ISSUE THREAD

**Issue by jcubic** [jacobwb/hashover-next#259]
Just got redirected to this url when logging out

https://example.com/hashover-next/hashover/admin/views/admin

witch don't exists

**Comment by jacobwb** [comment]
This is probably because of the change you made in #256, `$_SERVER['REQUEST_URI']` is not suitable for HashOver because it changes based on where the script is executing from. I have now made changes that should fix this issue, in the process I came across this same issue while using `$_SERVER['PHP_SELF']`, which is also not suitable for HashOver as it too changes. I can confirm that this issue does not occur for me, and I hope it is fixed for you as well.

Feel free to reopen this issue if the problem remains.
