### ISSUE TITLE
Guest Mode

### ISSUE THREAD

**Issue by el-ef** [jacobwb/hashover-next#266]
Hey there,

is there any option for an anonymous / guest mode, yet?
I would like to deactivate the 'Password', 'E-Mail' and 'Website' field for GDPR purposes, only allowing the user to choose a termporary nickname.

Regards,
el-ef

**Comment by CyberShadow** [comment]
I added the ability to enable/disable every field in #220 and #222, but Jacob decided to go his own way and not merge my changes.

**Comment by el-ef** [comment]
> 
> 
> I added the ability to enable/disable every field in #220 and #222, but Jacob decided to go his own way and not merge my changes.

Thanks for your contribution!
That's a real pity that there is no option to toggle the fields.

Do you know how I could fix it as a workaround?
I have tried excluding some fields via 'backend/classes/formui.php'. However, it does not work for the password field.

I just need a plain form, with a nickname and maybe a website field...

Regards
el-ef

**Comment by jacobwb** [comment]
Hello @el-ef, I'm glad to hear you found the solution yourself, sorry for the delay. HashOver was designed with absolute anonymity in mind. HashOver has supported disabling specific fields since before the official release of version 1.0, as far back as June 26, 2012 at least.

With that said, I have now made the form fields adjustable from the Admin Settings page.

**Comment by jacobwb** [comment]
Hello @CyberShadow, sorry for my silence, I will be trying to give HashOver a few hours of my time everyday from here on out. As to your pull request, I considered merging it multiple times, but I was unhappy with having the form field options as an array, because this prevented the local and front-end JSON settings loader from rejecting invalid settings.

My latest commits converts the form field options array into individual form field settings that are always strings, either `on`, `off` or `required`. And I have also added the settings to the Admin Settings page, so I have closed one of your pull requests. Thank you for the contributions and your continued interest and participation in the development of HashOver.

**Comment by carstengrimm** [comment]
awesome news @jacobwb i have followed hashover very recently and have also seen a few some reported issues (requests) and was wondering about how active the development is - as there were some pull requests too. 

and your reply just now is really great. i have just started using hashover and have not yet published it on any live site but i am looking forward to it. maybe when using hashover more i will be able to participate in a meaningful way to contribute looking for issues and bugs. 

keep up the good work!

**Comment by el-ef** [comment]
> 
> 
> With that said, I have now made the form fields adjustable from the Admin Settings page.

Thank you very much for that update and your kind response! :)

Is there also an option for toggling the "Login" button at the button (which will be redundant when hiding the password field)?

Regards
el-ef

**Comment by CyberShadow** [comment]
> As to your pull request, I considered merging it multiple times, but I was unhappy with having the form field options as an array, because this prevented the local and front-end JSON settings loader from rejecting invalid settings.

I would have been happy to perform those changes at your direction, had you voiced them shortly after I submitted the pull request. (Now, too much time has passed, the code is no longer fresh in my mind, and the master version has changed too much, so it would mean redoing the same amount of effort as which was needed to create the PR initially.)

**Comment by jacobwb** [comment]
@el-ef When you disable the name or password field the Login button should automatically disappear, because a name and password is required to login, so if either is disabled so is logging in. If you're logged in, you have to logout before the button disappears, though.

Should the Login button not automatically disappear -- that would be a bug, but -- on the Admin Settings page under the Login section there is an option "Allow users to login", uncheck it and this will remove the Login button and prevent people from logging in.

If you're after GDPR compliance, you might also be interested in disabling cookies altogether, the "Enable cookies" setting under the "Cookies" section. Unchecking this will disable logging in, as well as comment likes and dislikes, as those require cookies.

**Comment by el-ef** [comment]
@jacobwb 
Works like a charm, thanks again for the great support!

You could also add a custom text field, maybe to the left of the "Post Comment" button, for some privacy policy info or miscellaneous annotations.

Regards,
el-ef
