### ISSUE TITLE
AGPL'd HashOver + Closed Source Blog = AGPL Violation

### ISSUE THREAD

**Issue by techboyg5** [jacobwb/hashover-next#297]
Since HashOver uses the AGPL, it looks like your own blog's source code is not available.

You are not the sole copyright holder, since you accept pull requests from other people. Their contributions are copyrighted to them, and are licensed under the AGPL.

As a result, in order to comply with the AGPL, you must give people access to the source code of your own blog.

**Comment by jacobwb** [comment]
HashOver makes its own source code available by itself.

Here's mine: https://comments.barkdull.org/backend/source-viewer.php

My blog does not integrate the HashOver source code into its own. It only loads the AGPL JavaScript, which communicates to the AGPL PHP backend. Nowhere is my code mixed with the HashOver code, so all AGPL code is publicly available.

I would challenge that anyone has contributed anything substantial enough to legally be able to claim co-ownership, and so far most people who have contributed did so without adding themselves as a copyright holder, thus assigning the work to me. This is a moot point though, because as I said, all of the source code is publicly available.

Moreover, my blog is static. It is only a collection of HTML files and a few Apache rules to make the URLs nicer. Plus a few PHP scripts for the contact forms and the search engine, but HashOver isn't even used on those pages.

You seem to be pushing hard for a license change for some reason. What exactly are you planning on using my software for that you aren't willing to license the work under the AGPL?
