### ISSUE TITLE
Disable password field not working

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#47]
Previously I used

```
<script type="text/javascript">
        var passwd_on="no";  // Disables "Password" field
</script>
```

and the password + login button wouldn't be visible. Now they're shown regardless. 

What would be the equivalent with the new updates?

**Comment by Lux-Delux** [comment]
What would be equivalent now with the new code? Doesn't seem to work as is

**Comment by jacobwb** [comment]
@Lux-Delux

Just tested it, and it still works.

Important parts are `passwd_on` is now a proper `password_on` and uses `true` and `false` instead of `yes` and `no`, respectively. On your test page you're using `passwd_on` change that to `password_on`.

By the by, I really like the direction you're going with your theme so far.

Particularly the login inputs, I might go a similar direction myself...

![screenshot from 2015-03-21 04 28 56](https://cloud.githubusercontent.com/assets/4677622/6764870/5d41500a-cf83-11e4-90b6-24415a9bf7cf.png)
:-]

**Comment by Lux-Delux** [comment]
Ah, thanks.

Yeah them input fields turned pretty slick, feel free to use and abuse :)

Just started with the theme yesterday, am first trying to make it blend with my new website design which still isn't up.

We'll see how it will turn out and if there will need to be changes before I can put it here
