### ISSUE TITLE
Anti-spam measures: IP blocking and moderate function

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover-next#65]
Just got a human troll that posted a dozen spam comments. 

For this script we definitely need:
1. IP blocker
2. Moderate option

I guess this implementation would be easier with a database?

**Comment by jacobwb** [comment]
1. Is already implemented. Set the `$ip_addrs` variable to 'yes' to enable storing user IP addresses in their comments. Once you have the abusive IP address(es), add them, one per line, to a file named "blocklist.txt" in the "hashover" directory. You may also set the `$spam_IP_check` variable to either 'php', 'javascript' or 'both' to enable spam IP address checking against the database of spam server IP addresses maintained at stopforumspam.com.

  More information is in the documentation, under section "Need to block an IP address?": http://tildehash.com/?page=hashover

2. Would be implemented once the proposed "overview" is. Since moderation wouldn't be very easy without a central way to view and approve all comments.

**Comment by jacobwb** [comment]
You may also use a local CSV database if you want, I've discussed the performance of that approach among other things in issue https://github.com/jacobwb/hashover-next/issues/37. Though, SQLite would probably be faster, I'm not opposed to adding that functionality at some point.

**Comment by Lux-Delux** [comment]
Not directly related to hashover comments but a tip that I found very efficient and like to share around.

If you're running your own server/VPS you can easily setup a daily cron job that downloads an IP list from stopforumspam and then use that as a blocklist in apache/nginx/etc.

This way most of these bastards don't even get to reach your website, they're insta blocked by the web server

**Comment by jacobwb** [comment]
2 - See: #137
