### ISSUE TITLE
User without password can't edit first post

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#73]
Was just doing some testing and found this:

- User making first post enters just his name
- Submits post but can't edit that first post
- Submits second post and can edit that one

When I try a different user, this time with a password, he can immediately edit his first post.

**Comment by jacobwb** [comment]
The first comment should auto-login the user, without a password, and none of the comments posted that way should be editable. It turns out that the login related cookies were not set if they were empty. So the first comment is posted without a password, and the rest are posted with whatever password was set before the comment without a password was posted.

Simply a carryover from before the current login behavior was implemented.

It should be fixed now.
