### ISSUE TITLE
Write/parse comments improvements (fast markdown parsing?)

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#79]
I'd say this is a very important change. BR tags looks awful and styling them with css is very hacky.

Each line should be enclosed in `<p></p>`

Am checking out writecomments.php and got kind of spooked :p

**Comment by Lux-Delux** [comment]
Don't know what you would think of using this
https://github.com/erusev/parsedown

I had good experiences

**Comment by jacobwb** [comment]
Yes, `<br>` tags are to be replaced before 2.0's release. That is part of #62 messiness. Though, there's more wrong than just the `<br>` tags. Lines are stored as "\n", and by that I mean a literal backslash and an "n". Also comments are on one line, entire multiple-paragraph comments all on one line.

In the future a comment like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<comment>
	<name>...</name>
	<password>...</password>
	<email>...</email>
	<encryption>...</encryption>
	<website>...<website>
	<date>...</date>
	<body>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et massa sit amet nisl pellentesque elementum. Donec ac lacus a turpis pellentesque luctus. Donec venenatis hendrerit purus, ut bibendum enim luctus eget. Aenean tortor justo, fringilla non egestas et, lacinia interdum massa. Phasellus fringilla dui aliquam mauris adipiscing auctor. Aliquam aliquet scelerisque diam, in fringilla metus dapibus quis. Phasellus eget leo sed lacus mattis ultricies. Aenean auctor velit sit amet orci mattis pharetra. Nulla rhoncus varius tincidunt. &lt;br&gt;&lt;br&gt;\n\nDuis porta lacinia ultrices. Nunc ornare laoreet risus, in pulvinar tortor posuere non. Suspendisse tempor nibh at orci euismod congue. Nulla vulputate molestie pharetra. Nam commodo varius pellentesque. In consequat varius ipsum, et ultricies eros facilisis nec. Pellentesque orci orci, bibendum non aliquet eu, vulputate eu risus. Duis at ornare mauris. Aliquam erat volutpat. Nunc velit risus, ultrices quis mollis eget, rhoncus in sapien. Aliquam volutpat scelerisque purus, id viverra ipsum scelerisque vel. &lt;br&gt;&lt;br&gt;\n\nFusce at orci non arcu volutpat dapibus et nec nulla. Proin viverra laoreet urna, vel convallis diam consequat non. Nulla ut quam quis justo suscipit tincidunt. Vivamus vel feugiat leo. In a gravida nisl. Mauris pulvinar elit eget est tempus malesuada. Fusce adipiscing eros sed est tristique in eleifend elit congue. In semper sapien vitae purus rhoncus cursus. Mauris vitae arcu nec leo posuere aliquet non vel tortor. Ut pellentesque facilisis neque non feugiat. Aliquam blandit tellus est. Aenean laoreet facilisis neque, facilisis fringilla orci lobortis nec. Aliquam id nunc nibh, nec venenatis tortor. &lt;br&gt;&lt;br&gt;\n\nFusce lobortis interdum varius. Sed blandit lobortis enim, nec commodo risus facilisis vitae. Maecenas nec tellus tellus. Proin nibh augue, varius ac porta quis, posuere id nibh. Sed malesuada laoreet quam at pharetra. Maecenas vel arcu placerat diam tincidunt sollicitudin. Nunc elit ipsum, bibendum quis viverra vel, blandit eu elit. Etiam est eros, euismod vel placerat. &lt;br&gt;&lt;br&gt;\n\n</body>
	<likes>0</likes>
	<notifications>yes</notifications>
</comment>
```

Will look like:
```
<?xml version="1.0" encoding="UTF-8"?>
<comment>
	<name>...</name>
	<password>...</password>
	<email>...</email>
	<encryption>...</encryption>
	<website>...<website>
	<date>...</date>
	<likes>0</likes>
	<notifications>yes</notifications>

	<body>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et massa sit amet nisl
		pellentesque elementum. Donec ac lacus a turpis pellentesque luctus. Donec venenatis
		hendrerit purus, ut bibendum enim luctus eget. Aenean tortor justo, fringilla non egestas
		et, lacinia interdum massa. Phasellus fringilla dui aliquam mauris adipiscing auctor.
		Aliquam aliquet scelerisque diam, in fringilla metus dapibus quis. Phasellus eget leo sed
		lacus mattis ultricies. Aenean auctor velit sit amet orci mattis pharetra. Nulla rhoncus
		varius tincidunt.

		Duis porta lacinia ultrices. Nunc ornare laoreet risus, in pulvinar tortor posuere non.
		Suspendisse tempor nibh at orci euismod congue. Nulla vulputate molestie pharetra. Nam
		commodo varius pellentesque. In consequat varius ipsum, et ultricies eros facilisis nec.
		Pellentesque orci orci, bibendum non aliquet eu, vulputate eu risus. Duis at ornare mauris.
		Aliquam erat volutpat. Nunc velit risus, ultrices quis mollis eget, rhoncus in sapien.
		Aliquam volutpat scelerisque purus, id viverra ipsum scelerisque vel.

		Fusce at orci non arcu volutpat dapibus et nec nulla. Proin viverra laoreet urna, vel
		convallis diam consequat non. Nulla ut quam quis justo suscipit tincidunt. Vivamus vel
		feugiat leo. In a gravida nisl. Mauris pulvinar elit eget est tempus malesuada. Fusce
		adipiscing eros sed est tristique in eleifend elit congue. In semper sapien vitae purus
		rhoncus cursus. Mauris vitae arcu nec leo posuere aliquet non vel tortor. Ut pellentesque
		facilisis neque non feugiat. Aliquam blandit tellus est. Aenean laoreet facilisis neque,
		facilisis fringilla orci lobortis nec. Aliquam id nunc nibh, nec venenatis tortor.

		Fusce lobortis interdum varius. Sed blandit lobortis enim, nec commodo risus facilisis
		vitae. Maecenas nec tellus tellus. Proin nibh augue, varius ac porta quis, posuere id nibh.
		Sed malesuada laoreet quam at pharetra. Maecenas vel arcu placerat diam tincidunt
		sollicitudin. Nunc elit ipsum, bibendum quis viverra vel, blandit eu elit. Etiam est eros,
		euismod vel placerat.
	</body>
</comment>
```

Then, the comment will just have to be broken into paragraphs (`explode("\n\n", $comment);`) and returned to the JavaScript JSON with each paragraph wrapped in `<p>` tags.

This would make editing a comment in a text editor much easier and readable. It's kind of funny, because readability is one of the reasons XML is used to store the comments, and yet they're stored in such an ugly, hard to read and edit manner.

**Comment by jacobwb** [comment]
When it comes to parsedown, it seems to be actually quite slow, relatively. With the "[homebrew readme](http://parsedown.org/demo?example=homebrew_readme)" benchmark, which uses markdown for mostly everything HashOver parses now, I was getting an average parse time of 2.21 ms. That doesn't seem like much, but for 1,000 comments that's 2.21 seconds, for only 100 comments that's 0.22 seconds.

Considering the current execution time for 1,000 comments is 0.25 seconds, that would be a lot of overhead to add, particularly since I'm also trying to lower that execution time.

It's not really parsedown's fault, though. In general it's much faster to just do the parsing when saving the comment, and do no work when reading them. There's also the fact that some parsing needs to be done when saving anyway, for example you have to escape `<` and `>` before saving to XML, and there are similar problems for JSON, plus UTF-8 conversions, etc.

People comment far less then they read the comments, or the comments are displayed at least. To do parsing work for every comment for every random visitor would not be efficient.

**Comment by Lux-Delux** [comment]
Good points and glad to see a relevant performance estimate. Yeah makes no sense when you put it like that (I'm already using markdown for my posts so got  a little spoiled)

**Comment by jacobwb** [comment]
I would probably prefer to do it in a way where the user writes it in Markdown, but it's saved as HTML. Thereby removing the work on every load, while making it easy for the user.

Github here has a pretty nifty comment system, with the "Preview" tab and everything. That's what I'd personally go for, but with the comments being stored as HTML, which Github might be doing, I don't know. In other words, if it could be done in JavaScript then I might consider it. But again -- if you've noticed -- there is a noticeable delay when you click the "Preview" tab, and the longer the post the longer the delay. To do that with every comment might not be good either.

I will say, cleaning up the comments storage format (removing `<br>` tags, etc) is 2.0 stuff. Markdown and other frontend styling features is 2.1, barring any major bugs in 2.0.

**Comment by Lux-Delux** [comment]
Ooops forgot to comment on this. For now it would certainly be better if we had this output:

`<p class="hashover-paragraph">Bla bla bla</p>`

Basically if you inspect the html in the comments here on github that's what I mean. Then one can easily modify paragraph spacing with css.

**Comment by aoloe** [comment]
no need for class on each p: you  can probably already style all the p inside of the hashover area with css...

having markdown support would be a big plus for me.

personally, i'm intensively using <https://michelf.ca/projects/php-markdown/extra/> (which is almost github compatible) and i would love to see it in use here too, but i probably don't need all of its power for comments.

just a little bit of markdown would already be enough  :-)
