### ISSUE TITLE
Accessibility: add optional labels 

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#83]
I've been doing some research and while I visually love having only placeholders, not having labels is an accessibility problem.

e.g. https://longhandpixels.net/blog/2014/02/html5-placeholder-label-search-forms

Perhaps the best solution would be to add an option to display labels (for the inputs). So if someone doesn't want them they don't have to use css hacks to hide them.

Actually maybe best to have them on as default .

**Comment by jacobwb** [comment]
> "Just because a practice is widespread does not make it a *best* practice"

I couldn't disagree more. Popular consensus is the *only* way to measure accessibility.

Personally, I think the widespread use of placeholders without the need for labels is evidence that placeholders *do* work, just fine. If they truly caused accessibility issues would YouTube, GitHub, Twitter, Facebook, and Tumblr use them without labels? Likewise, other comment systems like Disqus, Google+ and Facebook comments use placeholder inputs without labels as well.

Not to mention the fact that software moved to remove labels in favor of placeholders long before most web browsers had the placeholder attribute. From Firefox and Chrome, to word processors and text editors, music players, image viewers, every major piece of smartphone and tablet software -- literally anywhere inputs show up in software nowadays, labels are not accompanying them.

With that said, I want to allow there to be labels if people want them.

So that designs like this are possible:

![untitled](https://cloud.githubusercontent.com/assets/4677622/6841267/947c18e2-d344-11e4-8c8e-18ba701914ba.png)

I personally think that looks ugly, but some people like it that way.

Ironically, though, once upon a time HashOver did have labels (but without `<label>` tags, I think) and they were removed when the old-style JavaScript placeholders became common place.

**Comment by Lux-Delux** [comment]
I agree they look ugly and personally won't use them but hey... if it's optional and not a lot of bloat why not. 

I'll correct myself by saying they should be optional. Sometimes I write stupidity late at night.
